#!/bin/bash
### Job Name
#PBS -N RNN-24
### Required runtime
#PBS -l walltime=48:00:00
### Queue for submission
#PBS -q cpu_a

### Submit array
#PBS -J 1-20

### Merge output and error files
#PBS -j oe

### Request memory and CPU cores
#PBS -l select=1:mem=12G:ncpus=1
job=$PBS_JOBNAME.$PBS_ARRAY_INDEX

### Start job in the currect directory
cd $PBS_O_WORKDIR

### Load Julia module
module load julia/1.6.0

### Run script
julia rnn_onehot.jl