#!/bin/bash
### Job Name
#PBS -N vent_12hours
### Required runtime
#PBS -l walltime=12:00:00
### Queue for submission
#PBS -q cpu_a

### Submit array of 50 jobs
#PBS -J 1-100

### Merge output and error files
#PBS -j oe

### Request memory and CPU cores
#PBS -l select=1:mem=8G:ncpus=1
job=$PBS_JOBNAME.$PBS_ARRAY_INDEX

### Start job in the currect directory
cd $PBS_O_WORKDIR

### Load Julia module
module load julia/1.6.0

### Run script
julia simple_run.jl